workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter packages pub get
      - name: Build APK
        script: |
          cd mobile
          flutter build apk --release
    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter packages pub get
      - name: Build iOS (no signing)
        script: |
          cd mobile
          flutter build ios --release --no-codesign
    artifacts:
      - mobile/build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com