name: new_api_admin
description: New API 移动端管理客户端
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^2.5.1

  # 网络请求
  dio: ^5.4.3

  # 本地存储
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # 路由
  go_router: ^14.0.2

  # UI 适配
  flutter_screenutil: ^5.9.0

  # 下拉刷新
  pull_to_refresh: ^2.0.0

  # 日期时间
  intl: ^0.19.0

  # Toast 提示
  fluttertoast: ^8.2.4

  # 加载指示器
  flutter_spinkit: ^5.2.1

  # 图表
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 应用图标和启动页
  # assets:
  #   - assets/images/

  # 字体配置（可选）
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf